import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  API_PORT: Joi.number().default(4000),
  DATABASE_URL: Joi.string().required(),
  PSQL_HOST: Joi.string().optional(),
  PSQL_PORT: Joi.number().optional(),
  PSQL_NAME: Joi.string().optional(),
  PSQL_USER: Joi.string().optional(),
  PSQL_PASSWORD: Joi.string().optional().allow(''),
  JWT_SECRET: Joi.string().min(16).required(),
  JWT_EXPIRES_IN: Joi.string().default('1d'),
  REDIS_URL: Joi.string().optional(),
  REDIS_HOST: Joi.string().optional(),
  REDIS_PORT: Joi.number().optional(),
  REDIS_PASSWORD: Joi.string().optional().allow(''),
  REDIS_DB: Joi.number().optional(),
  RABBITMQ_URL: Joi.string().optional(),
  RABBITMQ_QUEUE: Joi.string().optional(),
  RABBITMQ_PUBLISH_QUEUE: Joi.string().optional(),
  RABBITMQ_PREFETCH: Joi.number().optional(),
  AWS_REGION: Joi.string().optional(),
  AWS_S3_BUCKET: Joi.string().optional().allow(''),
  AWS_ACCESS_KEY_ID: Joi.string().optional().allow(''),
  AWS_SECRET_ACCESS_KEY: Joi.string().optional().allow(''),
  S3_ENDPOINT: Joi.string().optional(),
  INTEGRATION_WEBHOOK_SECRET: Joi.string().optional().allow(''),
  CORS_ORIGIN: Joi.string().optional(),
});
